#!/usr/bin/env ruby

require 'uri'

branch = `git branch | grep "^*" | cut -c 3-`.strip
remote = `git config branch.#{branch}.remote`.strip
urls = `git remote show #{remote} -n | egrep "^  (Fetch|Push )? URL: "`.strip.split("\n")
url = urls.first.split(":",2).last.strip
url.sub!(/^git@(.*):/,'git://\1/')
uri = URI.parse(url)  

if uri.host != "github.com"
  puts "Not a github repo (#{branch}/#{remote})"
  exit
end

username, project_name = uri.path.split("/",3)[1..-1]

project_name.sub!(/\.git$/,'')

puts "open \"http://github.com/#{username}/#{project_name}/tree/#{branch}\""
`open "http://github.com/#{username}/#{project_name}/tree/#{branch}"`
